#!/bin/zsh

alias ls='ls --color=auto -GF --quoting-style=literal'
alias ps='ps -e'
alias pause='mpc pause'
alias play='mpc play'
alias next='mpc next'
alias prev='mpc prev'
alias clear='mpc clear'
alias add='~/.myScripts/mpcAdd.sh title artist'
alias addall='~/.myScripts/mpcAdd.sh album artist'
alias addart='~/.myScripts/mpcAdd.sh artist album'
alias list='mpc playlist'
alias cmplayer='~/.myScripts/cmplayer.sh'
alias cuesplit='~/.myScripts/cuesplit.sh'
alias m4atomp3='~/.myScripts/m4aToMp3.sh'
alias idea='~/.myScripts/idea.sh'
alias music='cd /home/dimozzz/NTFS/sound'
alias video='cd /home/dimozzz/NTFS/dimon/south\ park/Разное'
alias wine='LANG=ru_RU.UTF-8 wine'
alias converttags='~/.myScripts/convertTags.sh'
alias aspellru='aspell -d ru -c'
alias aspellen='aspell -d en -c'
alias rtorr='sudo /etc/rc.d/rtorrentInit.sh'
alias emc='emacsclient -c'
alias mend='~/.myScripts/mend.sh'
